## task:0 
## Connect DuckDB

In [7]:
import duckdb
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

duckdb_path = "data/sakila.duckdb"
Path(duckdb_path).unlink(missing_ok=True)

with duckdb.connect(duckdb_path) as conn, open("sql/load_sakila_sqlite.sql") as ingest_script:
    conn.sql(ingest_script.read())

    description = conn.sql("DESC;").df()
    films = conn.sql("FROM film;").df()

films.head(3)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,<NA>,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2021-03-06 15:52:00
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,<NA>,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2021-03-06 15:52:00
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,<NA>,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2021-03-06 15:52:00

In [9]:
description.head()

,database,schema,name,column_names,column_types,temporary
0,sakila,main,actor,"[actor_id, first_name, last_name, last_update]","[DOUBLE, VARCHAR, VARCHAR, TIMESTAMP]",False
1,sakila,main,address,"[address_id, address, address2, district, city...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGINT, VA...",False
2,sakila,main,category,"[category_id, name, last_update]","[BIGINT, VARCHAR, TIMESTAMP]",False
3,sakila,main,city,"[city_id, city, country_id, last_update]","[BIGINT, VARCHAR, BIGINT, TIMESTAMP]",False
4,sakila,main,country,"[country_id, country, last_update]","[BIGINT, VARCHAR, TIMESTAMP]",False

## Some code from lecture 18 as help to read in all data into dictionary of panda DataFrames

In [10]:
dfs = {}

with duckdb.connect(duckdb_path) as conn:
    for name in description["name"]:
        dfs[name] = conn.sql(f"FROM {name};").df()

dfs.keys()

dict_keys(['actor', 'address', 'category', 'city', 'country', 'customer', 'customer_list', 'film', 'film_actor', 'film_category', 'film_list', 'film_text', 'inventory', 'language', 'payment', 'rental', 'sales_by_film_category', 'sales_by_store', 'staff', 'staff_list', 'store'])

In [11]:
dfs["film_actor"].head()

   actor_id  film_id         last_update
0         1        1 2021-03-06 15:52:45
1         1       23 2021-03-06 15:52:45
2         1       25 2021-03-06 15:52:45
3         1      106 2021-03-06 15:52:45
4         1      140 2021-03-06 15:52:45

##  Time to register all data in duckdb, referens from lecture 18.

In [14]:
tbl_names = ('actor', 'address', 'category', 'city', 'country', 'customer', 
              'customer_list','film', 'film_actor', 'film_category', 'film_list', 
              'film_text', 'inventory', 'language', 'payment', 'rental', 
              'sales_by_film_category', 'sales_by_store', 'staff', 'staff_list', 'store')

for tbl_name in tbl_names:
    duckdb.register(tbl_name, dfs[tbl_name])

duckdb.sql("desc;").df()

,database,schema,name,column_names,column_types,temporary
0,temp,main,actor,"[actor_id, first_name, last_name, last_update]","[DOUBLE, VARCHAR, VARCHAR, TIMESTAMP]",True
1,temp,main,address,"[address_id, address, address2, district, city...","[BIGINT, VARCHAR, ""NULL"", VARCHAR, BIGINT, VAR...",True
2,temp,main,category,"[category_id, name, last_update]","[BIGINT, VARCHAR, TIMESTAMP]",True
3,temp,main,city,"[city_id, city, country_id, last_update]","[BIGINT, VARCHAR, BIGINT, TIMESTAMP]",True
4,temp,main,country,"[country_id, country, last_update]","[BIGINT, VARCHAR, TIMESTAMP]",True
5,temp,main,customer,"[customer_id, store_id, first_name, last_name,...","[BIGINT, BIGINT, VARCHAR, VARCHAR, VARCHAR, BI...",True
6,temp,main,customer_list,"[ID, name, address, zip_code, phone, city, cou...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, V...",True
7,temp,main,film,"[film_id, title, description, release_year, la...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGINT, BI...",True
8,temp,main,film_actor,"[actor_id, film_id, last_update]","[BIGINT, BIGINT, TIMESTAMP]",True
9,temp,main,film_category,"[film_id, category_id, last_update]","[BIGINT, BIGINT, TIMESTAMP]",True
10,temp,main,film_list,"[FID, title, description, category, price, len...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, DOUBLE, BI...",True
11,temp,main,film_text,"[film_id, title, description]","[BIGINT, ""NULL"", ""NULL""]",True
12,temp,main,inventory,"[inventory_id, film_id, store_id, last_update]","[BIGINT, BIGINT, BIGINT, TIMESTAMP]",True
13,temp,main,language,"[language_id, name, last_update]","[BIGINT, VARCHAR, TIMESTAMP]",True
14,temp,main,payment,"[payment_id, customer_id, staff_id, rental_id,...","[BIGINT, BIGINT, BIGINT, BIGINT, DOUBLE, TIMES...",True
15,temp,main,rental,"[rental_id, rental_date, inventory_id, custome...","[BIGINT, TIMESTAMP, BIGINT, BIGINT, TIMESTAMP,...",True
16,temp,main,sales_by_film_category,"[category, total_sales]","[VARCHAR, DOUBLE]",True
17,temp,main,sales_by_store,"[store_id, store, manager, total_sales]","[BIGINT, VARCHAR, VARCHAR, DOUBLE]",True
18,temp,main,staff,"[staff_id, first_name, last_name, address_id, ...","[BIGINT, VARCHAR, VARCHAR, BIGINT, ""NULL"", VAR...",True
19,temp,main,staff_list,"[ID, name, address, zip_code, phone, city, cou...","[BIGINT, VARCHAR, VARCHAR, ""NULL"", VARCHAR, VA...",True
20,temp,main,store,"[store_id, manager_staff_id, address_id, last_...","[BIGINT, BIGINT, BIGINT, TIMESTAMP]",True