## task:0 
## Connect DuckDB

In [2]:
import duckdb # importing library duckdb
import pandas as pd # importing library pandas

conn = duckdb.connect("data/sakila.duckdb") # connecting to the database sakila.duckdb

with open ("sql/load_sakila_sqlite.sql") as f:
    conn.execute(f.read()) # loading the sakila database schema and data

films = conn.execute("""
    SELECT *
    FROM film
    LIMIT 3
""").df()

films
# displaying the first 3 rows of the film table

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,<NA>,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2021-03-06 15:52:00
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,<NA>,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2021-03-06 15:52:00
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,<NA>,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2021-03-06 15:52:00

In [5]:
description = conn.execute("""
        SELECT *
         FROM information_schema.columns
         LIMIT 5
""").df() # getting the first 5 rows of the information_schema.columns table 
description

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable,COLUMN_COMMENT
0,sakila,main,actor,actor_id,1,None,YES,DOUBLE,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
1,sakila,main,actor,first_name,2,None,YES,VARCHAR,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
2,sakila,main,actor,last_name,3,None,YES,VARCHAR,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
3,sakila,main,actor,last_update,4,None,YES,TIMESTAMP,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None
4,sakila,main,address,address_id,1,None,YES,BIGINT,<NA>,<NA>,...,None,None,None,None,None,<NA>,None,None,<NA>,None